# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Darío Suárez Gracia
title: Darío Suárez Gracia
email: dario@unizar.es
description: > # this means to ignore newlines until "url:"
    A simple webpage for Darío Suárez Gracia. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: '//webdiis.unizar.es' # the base hostname & protocol for your site
baseurl: '/~dario' # the subpath of your site, e.g. /blog/
last_updated: December 18, 2019

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: dariosg # put your github username
twitter_username: dariosugr # put your twitter username
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL

linkedin_username: dariosuarezgracia # put your linkedin username
scholar_userid: GMN3oxEAAAAJ # put your google scholar author id
orcid_id: 0000-0002-7490-4067
researchgate_username:  Dario_Suarez_Gracia # put your ResearchGate username  <a href="https://www.researchgate.net/profile/Dario_Suarez_Gracia">Darío Suárez Gracia on ResearchGate</a>
contact_note: >
  Please fell free to reach out to me by email.

# google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name:
blog_description: 

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true
enable_google_analytics: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
    #projects:
    #output: false
    #permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji
    - jekyll-compress-images
    - Jekyll-gzip

# Jekyll-Scholar
scholar:

  last_name: Suarez Gracia

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

image_optim:
  pngout: false
  svgo: false
  verbose: false

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
